<?php

namespace Tests\Feature\Ussd;

use App\Models\App;
use App\Models\ShortCode;
use App\Models\Version;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Support\FirstAidApp;
use Tests\TestCase;

/**
 * Validates the FirstAidApp seeder produces a faithful, runnable app graph so
 * the golden-master engine tests have a real builder to execute against.
 *
 * @group harness
 */
class FixtureSeederTest extends TestCase
{
    use RefreshDatabase;

    public function test_it_stands_up_the_full_app_graph(): void
    {
        $app = FirstAidApp::create();

        $this->assertDatabaseHas('projects', ['id' => $app->project->id]);
        $this->assertDatabaseHas('apps', [
            'id' => $app->app->id,
            'active_version_id' => $app->version->id,
        ]);
        $this->assertDatabaseHas('versions', [
            'id' => $app->version->id,
            'app_id' => $app->app->id,
        ]);
        $this->assertDatabaseHas('short_codes', [
            'id' => $app->shortCode->id,
            'dedicated_code' => '*217#',
            'app_id' => $app->app->id,
        ]);
        // shared_code is generated by the ShortCodeObserver from "*100#".
        $this->assertStringStartsWith('*100*', $app->sharedCode);
    }

    public function test_saved_builder_retains_the_flow_topology(): void
    {
        $app = FirstAidApp::create();

        // Reload from the DB to confirm what actually persisted (post-repairBuilder).
        $builder = Version::find($app->version->id)->builder;

        $this->assertIsArray($builder);
        $this->assertCount(19, $builder['screens'], 'Expected 19 screens after save.');

        $displays = 0;
        foreach ($builder['screens'] as $screen) {
            $displays += count($screen['displays'] ?? []);
        }
        $this->assertSame(35, $displays, 'Expected 35 displays after save.');
    }

    public function test_raw_fixture_matches_documented_audit_counts(): void
    {
        // These are the exact numbers the performance docs audited against the
        // real First-Aid builder — they anchor the File 03 upgrader tests.
        $builder = FirstAidApp::rawBuilder();

        $this->assertCount(19, $builder['screens']);
        $this->assertSame('26778705094', $builder['simulator']['subscriber']['phone_number']);
        $this->assertSame(120, $builder['simulator']['settings']['timeout_limit_in_seconds']);
        $this->assertArrayHasKey('color_scheme', $builder);
    }
}
